(ns tursas.state0x88.common)

(def WHITE-KING-STORE 0x0c)
(def BLACK-KING-STORE 0x7c)
(def TURN-STORE 0x38)
(def HALF-MOVE-STORE 0x39)
(def FULL-MOVE-N-STORE 0x3a)
(def FULL-MOVE-STORE 0x3b)
(def CASTLING-STORE 0x58)
(def EN-PASSANT-STORE 0x59)
(def DYNAMIC-STORE 0x5a)

(def CHECK-STORE 0x5b)

(def PREV-MOVE-FROM 0x6a)
(def PREV-MOVE-TO 0x6b)
(def PREV-PIECE 0x6c)

(def WHITE-KING-SIDE 8)
(def WHITE-QUEEN-SIDE 4)
(def BLACK-KING-SIDE 2)
(def BLACK-QUEEN-SIDE 1)

(def KING-SIDE 1)
(def QUEEN-SIDE 0)

(def WHITE 0)
(def BLACK 1)

(def BLACK-QUEEN -6)
(def BLACK-ROOK -5)
(def BLACK-BISHOP -4)
(def BLACK-KING -3)
(def BLACK-KNIGHT -2)
(def BLACK-PAWN -1)

(def EMPTY 0)

(def WHITE-PAWN 1)
(def WHITE-KNIGHT 2)
(def WHITE-KING 3)
(def WHITE-BISHOP 4)
(def WHITE-ROOK 5)
(def WHITE-QUEEN 6)

(def NORTH 16)
(def NN 32)
(def SOUTH -16)
(def SS -32)
(def EAST 1)
(def WEST -1)
(def NE 17)
(def SW -17)
(def NW 15)
(def SE -15)
